### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by masterchen** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#1]
in which case we need this? thanks

**Comment by avishnyak** [comment]
Hi @masterchen,

This library is a completely optional addon to MQTTnet (i.e. it is never required).  You would WANT to use this if:

- Your primary use case is validating/processing the MQTT messages on your server
- Your server is not primarily sending data to clients via MQTT
- You appreciate encapsulating your message processing logic in controllers in a way similar to AspNetCore and WebAPI

You can do everything that this addon does directly by using MQTTnet delegates yourself, but I created this addon because I like the organization that Controllers provide as your logic grows.
