### ISSUE TITLE
How to connect?

### ISSUE THREAD

**Issue by tobi4321** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#2]
If i run your example, what are the credentials to connect to this mqtt controller?
I tried to connect via NodeRed mqtt Node with ip of the Computer where VS is running, port 1883 but node red says connection error... 
Can you please describe how i can call the WeatherReport Function?

**Comment by avishnyak** [comment]
The limitation of using MQTT with AspNetCore in general is that you can only use the websocket version of the connection.  So make sure that you:

* Connect using WS or WSS
* Connect on the same port that you set up Kestrel or IIS to listen for incoming connections (see: [
ASP.NET Core 3.1+](https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-core-31-since-mqtt-version-309) where it says "ListenAnyIP")

This library doesn't change anything about how MQTT server listens for incoming connections so you may get more help on StackOverflow or on the [chkr1011/MQTTnet repo](https://github.com/chkr1011/MQTTnet)

**Comment by redradist** [comment]
The same issue ... I tried to use MQTT.js library https://github.com/mqttjs/MQTT.js that supports ws and wss, but neither works ...

Test connection to eclipse works !!
Seems like some issue with server configuration ...

**Comment by redradist** [comment]
@avishnyak I have tested https://github.com/SeppPenner/SimpleMqttServer/blob/master/SimpleMqttServer and this example works, I was able to connect using https://www.nuget.org/packages/MQTTnet.Extensions.ManagedClient/ to server ... seems like I cannot launch only AttributeRouting example ...
Seems like missed some server StartAsync command ?

**Comment by redradist** [comment]
@avishnyak Could you maybe provide some simple example using https://www.nuget.org/packages/MQTTnet.Extensions.ManagedClient/  how to connect to your example using WebSocket in C# ?

I will be very appreciated :)

**Comment by avishnyak** [comment]
I have added an example client using ManagedClient here: https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting/tree/master/ExampleClient

Note that this library does not do anything specific to connections.  It only handles routing after MQTTnet actually establishes the connection.

**Comment by redradist** [comment]
> 
> 
> I have added an example client using ManagedClient here: https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting/tree/master/ExampleClient
> 
> Note that this library does not do anything specific to connections. It only handles routing after MQTTnet actually establishes the connection.

@avishnyak Thanks a lot !!
